### ISSUE TITLE
Three or four high-level categories?

### ISSUE THREAD

**Issue by jpotvin** [Xalgorithms/general-documentation#22]
RE:  the projects .. fall into three high-level categories: Lichen, XADF, Authoring

I'd have described the Xalgo specification itself as a high-level category. Are you certain about it being internal to the authoring sub-project?

Also, I'd call the authoring sub-project "XalgoAuthor" or something like that.

~joseph

**Comment by karfai** [comment]
I don't write that it's internal to authoring... But... It's worthwhile as a category.

**Comment by karfai** [comment]
Integrated into the changes for #21 (https://github.com/Xalgorithms/xa-arch/commit/4dae54d48662d1f7e1ff9fe64defe0db4cb37065)

**Comment by jpotvin** [comment]
I didn't really mean to say you did make it internal -- I guess I just didn't know where it would be if it were not one of the high-level 'projects'.
