### ISSUE TITLE
Add an additional conclusion about inference systems

### ISSUE THREAD

**Issue by karfai** [Xalgorithms/general-documentation#45]
FEATURE: https://github.com/Xalgorithms/interlibr/issues/47

In (), we make some conclusions about *what* Interlibr is and does. In the document conclusion, we talk about some of the categories, but we don't make any comments about inference systems. Since these are a big part of the landscape, there should be a paragraph in the conclusion about them.

**Comment by wolders** [comment]
And machine learning. Data aggregation.

William Olders
613-762-9383
